import constants from "./Constants";

export default {
  actionBar: "LOM_GUI_01.png",
  healthBar: "LOM_GUI_02.png",
  potionBar: "LOM_GUI_10.png",
  actionPointsBar: "LOM_GUI_04.png",
  experienceBarFrame: "LOM_GUI_37.png",
  experienceBar: "LOM_GUI_08.png",
  emptyStatusBar: "LOM_GUI_03.png",
  statusBarFrame: "LOM_GUI_07.png",
  // hudFrameBase: "LOM_GUI_12.png",
  hudFrameBase: "LOM_GUI_12_Complete.png",
  itemInfoPanelBase: "LOM_GUI_15.png",
  dialog: "LOM_GUI_53.png",
  itemInfo: {
    common: {
      header: "LOM_GUI_18.png",
      color: "white",
    },
    magic: {
      header: "LOM_GUI_13.png",
      color: "white",
    },
    rare: {
      header: "LOM_GUI_17.png",
      color: constants.styles.text.colors.Info,
    },
  },
  strengthRing: "LOM_GUI_26.png",
  intelligenceRing: "LOM_GUI_27.png",
  dexterityRing: "LOM_GUI_28.png",
  scrollBarButton: "LOM_GUI_16.png",
  potionSlot: {
    base: "LOM_GUI_09.png",
    hover: "",
  },
  itemSlot: {
    base: "LOM_GUI_05.png",
    hover: "LOM_GUI_06.png",
    nftFrame: "LOM_GUI_69.png",
    potions: "LOM_GUI_73.png",
    potions_hover: "LOM_GUI_75.png",
  },
  actionBarBackground: "LOM_GUI_74.png",
  // inventoryPanel: "LOM_GUI_11.png",
  inventoryPanel: "InventoryPanel.png",
  // characterSheetPanel: "LOM_GUI_19.png",
  characterSheetPanel: "LOM_GUI_ScaleTest1.png",
  levelFrame: "LOM_GUI_62.png",
  // healthSphere: "LOM_GUI_29.png",
  healthSphere: "LOM_GUI_33.png",
  sphereDecorationRight: "LOM_GUI_72.png",
  sphereFrame: "LOM_GUI_31.png",
  sphereOuterFrame: "LOM_GUI_34.png",
  sphereBackground: "LOM_GUI_36.png",
  apSphere: "LOM_GUI_35.png",
  shopWindow: "LOM_GUI_38.png",
  buttons: {
    green: {
      base: "LOM_GUI_50.png",
      // base: "LOM_GUI_39.png",
      hover: "LOM_GUI_40.png",
    },
    maroon: {
      base: "LOM_GUI_65.png",
      hover: "LOM_GUI_70.png",
    },
  },
  buttons2: {
    green: {
      base: {
        top: "LOM_GUI_47.png",
        bottom: "LOM_GUI_48.png",
        topLeft: "LOM_GUI_43.png",
        topRight: "LOM_GUI_44.png",
        bottomLeft: "LOM_GUI_43.png",
        bottomRight: "LOM_GUI_45.png",
        inside: "LOM_GUI_49.png",
      },
    },
  },
  balance: {
    equal: "LOM_GUI_41.png",
    unequal: "LOM_GUI_42.png",
  },
  thumbSlider: "LOM_GUI_51.png",
  sliderFrame: "LOM_GUI_52.png",
  socketEditor: "LOM_GUI_54.png",
  inventory: {
    headerBackground: "LOM_GUI_57.png",
    headerStamp: "LOM_GUI_58.png",
    mainFrame: "LOM_GUI_56.png",
    gridFrame: "LOM_GUI_55.png",
    innerFrame_left: "LOM_GUI_59.png",
    innerFrame_right: "LOM_GUI_61.png",
  },
  ornament: "LOM_GUI_60.png",
  skillGrid: "LOM_GUI_63.png",
  skillGridTop: "LOM_GUI_64.png",
  statusIcons: {
    bleeding: "LOM_GUI_66.png",
    poisoned: "LOM_GUI_67.png",
    shocked: "LOM_GUI_68.png",
  },
  quest: {
    exclamation: "LOM_GUI_71.png",
  },
};
